project_name: ingress-controller
release:
  github:
    owner: qumine
    name: ingress-controller
  prerelease: auto
before:
  hooks:
  - go mod download
builds:
- goos:
  - linux
  goarch:
  - amd64
  - arm64
  goarm:
  - 6
  - 7
  binary: ingress-controller
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s
  - -w
  - -X github.com/qumine/ingress-controller/pkg/build.version={{ .Version }}
  - -X github.com/qumine/ingress-controller/pkg/build.commit={{ .FullCommit }}
  - -X github.com/qumine/ingress-controller/pkg/build.date={{ .Date }}
archives:
- id: tar_gz
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dockers:
- dockerfile: build/package/Dockerfile
  image_templates:
  - "qumine/ingress-controller:latest-amd64"
  - "qumine/ingress-controller:{{.Tag}}-amd64"
  goos: linux
  goarch: amd64
  ids:
  - ingress-controller
  build_flag_templates:
  - "--build-arg=ARCH=amd64/"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/ingress-controller"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/ingress-controller"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
- dockerfile: build/package/Dockerfile
  image_templates:
  - "qumine/ingress-controller:latest-arm64v8"
  - "qumine/ingress-controller:{{.Tag}}-arm64v8"
  goos: linux
  goarch: arm64
  ids:
  - ingress-controller
  build_flag_templates:
  - "--build-arg=ARCH=arm64v8/"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.description={{ .ProjectName }}"
  - "--label=org.opencontainers.image.url=https://github.com/qumine/ingress-controller"
  - "--label=org.opencontainers.image.source=https://github.com/qumine/ingress-controller"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.licenses=AGPL-3.0"
docker_manifests:
- name_template: qumine/ingress-controller:latest
  image_templates:
  - qumine/ingress-controller:latest-amd64
  - qumine/ingress-controller:latest-arm64v8
- name_template: qumine/ingress-controller:{{.Tag}}
  image_templates:
  - qumine/ingress-controller:{{.Tag}}-amd64
  - qumine/ingress-controller:{{.Tag}}-arm64v8
changelog:
  filters:
    exclude:
    - '^ci:'
    - '^docs:'
    - '^misc:'
    - '^test:'
